;- VIC-20 Unit Tests - Copyright 2026 Fabio Carignano ------------------------

;- GLOBAL ZERO PAGE VARIABLES ------------------------------------------------
.globalzp zInputJyst, zInputKbd1, zInputKbd2, zInputKbd4, zInputKbd5

;- GLOBAL SUBROUTINES --------------------------------------------------------
.global input_init, input_scan

;-----------------------------------------------------------------------------
