name: build

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cc65 make

      - name: Build
        run: make -C src

      - name: Upload binaries
        uses: actions/upload-artifact@v6
        with:
          name: VIC20-StarWanderer
          path: |
            bin/starwanderer.prg
